apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: apps
spec:
  releaseName: redis
  serviceAccountName: dev-team
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: apps
      version: 17.1.5
  interval: 5m
